class AppStrings {
  static const String appName = 'Fury';
  static const String noInternet = 'No Internet Connection';
  static const String refresh = 'Refresh';
  static const String signIn = 'Sign in';
  static const String signOut = 'Sign out';
  static const String resetPassword = 'Reset';
  static const String emailAddress = 'Email Address';
  static const String userName = 'User Name';
  static const String password = 'Password';
  static const String login = 'Login';
  static const String noAccount = "Don't have an account? ";
  static const String forgetPassword = "Forget password? ";
  static const String signUp = "Sign Up";
  static const String register = "Register";
  static const String firstName = "First Name";
  static const String lastName = "Last Name";
  static const String popularMovies = "Popular Movies";
  static const String nowPlayingMovies = "Now Playing Movies";
  static const String upComingMovies = "New Releases";
  static const String topRatedMovies = "Top Rated Movies";
  static const String tvAiringToday = "TV Airing Today";
  static const String popularTv = "Popular TV Shows";
  static const String topRatedTv = "Top Rated Tv Shows";
  static const String trendingMovies = "Trending Movies";
  static const String home = " Home";
  static const String movies = " My Movies";
  static const String news = " News";
  static const String settings = " Settings";
  static const String emailAndPassword = "Please enter email and password";
  static const String hottestNews = "Hottest News";
  static const String explore = "Explore";
  static const String business = "Business";
  static const String health = "Health";
  static const String sports = "Sports";
  static const String science = "Science";
  static const String technology = "Technology";
  static const String search = "Search";
  static const String genre = "Genre";
  static const String noData = "No data available";
  static const String later = "Later";
  static const String favorite = "Favorite";
  static const String similarMovies = "Similar Movies";
  static const String similarTVShows = "Similar TV Shows";
  static const String noSimilarMovies =
      "Sorry, There are no similar movies available for this movie";
  static const String noSimilarTVShows =
      "Sorry, There are no similar TV shows available for this movie";
}
